baseURL = "https://stardrop-berry-rage.github.io"
languageCode = "en-us"
title = "RAGE for ANUSA"
#theme = "anusa-campaign" # You can name your theme anything

[taxonomies]
  role_type = "role_types"

[params]
  # --- Branding ---
  # These can be changed for any future campaign
  ticket_name = "RAGE for ANUSA"
  description = "Angry about the same things you are."
  logo_font = "Anton"
  primary_color = "#000000"
  secondary_color = "#FFFFFF" # White
  accent_color = "#FF3366"

  # --- Google Fonts ---
  # URL to import the font families you want to use
  google_fonts_url = "https://fonts.googleapis.com/css2?family=Anton&family=Lato:wght@400;700&display=swap"
